In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import os
import random

from utils import read_table

In [7]:
df = read_table("Batting")

In [8]:
df.head(50)

,playerID,yearID,stint,teamID,lgID,G,AB,R,H,2B,...,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
0,abadan01,2001,1,OAK,AL,1,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,abadan01,2003,1,BOS,AL,9,17.0,1.0,2.0,0.0,...,0.0,0.0,1.0,2.0,5.0,0.0,0.0,0.0,0.0,1.0
2,abadan01,2006,1,CIN,NL,5,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
3,abbotje01,1997,1,CHA,AL,19,38.0,8.0,10.0,1.0,...,2.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,3.0
4,abbotje01,1998,1,CHA,AL,89,244.0,33.0,68.0,14.0,...,41.0,3.0,3.0,9.0,28.0,1.0,0.0,2.0,5.0,2.0
5,abbotje01,1999,1,CHA,AL,17,57.0,5.0,9.0,0.0,...,6.0,1.0,1.0,5.0,12.0,0.0,0.0,1.0,1.0,4.0
6,abbotje01,2000,1,CHA,AL,80,215.0,31.0,59.0,15.0,...,29.0,2.0,1.0,21.0,38.0,1.0,2.0,2.0,1.0,2.0
7,abbotje01,2001,1,FLO,NL,28,42.0,5.0,11.0,3.0,...,5.0,0.0,0.0,3.0,7.0,0.0,1.0,0.0,0.0,1.0
8,abbotji01,1989,1,CAL,AL,29,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,abbotji01,1990,1,CAL,AL,33,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,abbotji01,1991,1,CAL,AL,34,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,abbotji01,1992,1,CAL,AL,29,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,abbotji01,1993,1,NYA,AL,32,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,abbotji01,1994,1,NYA,AL,24,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,abbotji01,1995,1,CHA,AL,17,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,abbotji01,1995,2,CAL,AL,13,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,abbotji01,1996,1,CAL,AL,27,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,abbotji01,1998,1,CHA,AL,5,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,abbotji01,1999,1,MIL,NL,20,21.0,0.0,2.0,0.0,...,3.0,0.0,0.0,0.0,10.0,0.0,0.0,3.0,0.0,1.0
19,abbotku01,1993,1,OAK,AL,20,61.0,11.0,15.0,1.0,...,9.0,2.0,0.0,3.0,20.0,0.0,0.0,3.0,0.0,3.0
20,abbotku01,1994,1,FLO,NL,101,345.0,41.0,86.0,17.0,...,33.0,3.0,0.0,16.0,98.0,1.0,5.0,3.0,2.0,5.0
21,abbotku01,1995,1,FLO,NL,120,420.0,60.0,107.0,18.0,...,60.0,4.0,3.0,36.0,110.0,4.0,5.0,2.0,5.0,6.0
22,abbotku01,1996,1,FLO,NL,109,320.0,37.0,81.0,18.0,...,33.0,3.0,3.0,22.0,99.0,1.0,3.0,4.0,0.0,7.0
23,abbotku01,1997,1,FLO,NL,94,252.0,35.0,69.0,18.0,...,30.0,3.0,1.0,14.0,68.0,3.0,1.0,6.0,0.0,5.0
24,abbotku01,1998,1,OAK,AL,35,123.0,17.0,33.0,7.0,...,9.0,2.0,1.0,10.0,34.0,0.0,1.0,1.0,1.0,3.0
25,abbotku01,1998,2,COL,NL,42,71.0,9.0,18.0,6.0,...,15.0,0.0,0.0,2.0,19.0,0.0,1.0,0.0,2.0,2.0
26,abbotku01,1999,1,COL,NL,96,286.0,41.0,78.0,17.0,...,41.0,3.0,2.0,16.0,69.0,0.0,0.0,2.0,1.0,4.0
27,abbotku01,2000,1,NYN,NL,79,157.0,22.0,34.0,7.0,...,12.0,1.0,1.0,14.0,51.0,2.0,1.0,0.0,1.0,2.0
28,abbotku01,2001,1,ATL,NL,6,9.0,0.0,2.0,0.0,...,0.0,1.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0
29,abbotky01,1991,1,CAL,AL,5,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,abbotky01,1992,1,PHI,NL,31,29.0,1.0,2.0,1.0,...,2.0,0.0,0.0,1.0,18.0,0.0,0.0,6.0,0.0,0.0
31,abbotky01,1995,1,PHI,NL,18,2.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
32,abbotky01,1996,1,CAL,AL,3,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,abbotpa01,1990,1,MIN,AL,7,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,abbotpa01,1991,1,MIN,AL,15,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35,abbotpa01,1992,1,MIN,AL,6,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,abbotpa01,1993,1,CLE,AL,5,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,abbotpa01,1998,1,SEA,AL,4,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,abbotpa01,1999,1,SEA,AL,25,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39,abbotpa01,2000,1,SEA,AL,35,5.0,1.0,2.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
40,abbotpa01,2001,1,SEA,AL,28,4.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
41,abbotpa01,2002,1,SEA,AL,7,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42,abbotpa01,2003,1,KCA,AL,10,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
43,abbotpa01,2004,1,TBA,AL,10,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44,abbotpa01,2004,2,PHI,NL,10,11.0,1.0,2.0,0.0,...,2.0,0.0,0.0,0.0,4.0,0.0,0.0,3.0,0.0,0.0
45,abercre01,2006,1,FLO,NL,111,255.0,39.0,54.0,12.0,...,24.0,6.0,5.0,18.0,78.0,2.0,3.0,4.0,1.0,2.0
46,abercre01,2007,1,FLO,NL,35,76.0,16.0,15.0,3.0,...,5.0,7.0,1.0,2.0,22.0,0.0,2.0,0.0,0.0,1.0
47,abercre01,2008,1,HOU,NL,34,55.0,10.0,17.0,5.0,...,5.0,5.0,2.0,1.0,23.0,0.0,2.0,1.0,1.0,0.0
48,abernbr01,2001,1,TBA,AL,79,304.0,43.0,82.0,17.0,...,33.0,8.0,3.0,27.0,35.0,1.0,0.0,3.0,1.0,3.0
49,abernbr01,2002,1,TBA,AL,117,463.0,46.0,112.0,18.0,...,40.0,10.0,4.0,25.0,46.0,0.0,6.0,8.0,2.0,8.0

In [9]:
def check_nan_columns(df):
    nan_columns = df.isna().any()
    return nan_columns
check_nan_columns(df)

playerID    False
yearID      False
stint       False
teamID      False
lgID        False
G           False
AB           True
R            True
H            True
2B           True
3B           True
HR           True
RBI          True
SB           True
CS           True
BB           True
SO           True
IBB          True
HBP          True
SH           True
SF           True
GIDP         True
dtype: bool