In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from utils import read_table

In [3]:
df_bat = read_table("PlayerBatting")

In [4]:
df_bat.head()

,Unnamed: 0,playerID,yearID,stint,teamID,lgID,G,AB,R,H,...,HBP,SH,SF,GIDP,birthYear,weight,height,debut,current_age,years_of_experience
0,0,abbotku01,1993,1,OAK,AL,20,61.0,11.0,15.0,...,0.0,3.0,0.0,3.0,1969.0,180.0,71.0,1993-09-07,24.0,0
1,1,abbotku01,1994,1,FLO,NL,101,345.0,41.0,86.0,...,5.0,3.0,2.0,5.0,1969.0,180.0,71.0,1993-09-07,25.0,1
2,2,abbotku01,1995,1,FLO,NL,120,420.0,60.0,107.0,...,5.0,2.0,5.0,6.0,1969.0,180.0,71.0,1993-09-07,26.0,2
3,3,abbotku01,1996,1,FLO,NL,109,320.0,37.0,81.0,...,3.0,4.0,0.0,7.0,1969.0,180.0,71.0,1993-09-07,27.0,3
4,4,abbotku01,1997,1,FLO,NL,94,252.0,35.0,69.0,...,1.0,6.0,0.0,5.0,1969.0,180.0,71.0,1993-09-07,28.0,4

In [5]:
print(df_bat.to_string())

KeyboardInterrupt:

In [6]:
# R = you score
# AB + BB + IBB + HBP = PA
# statistics to keep track
# On base percentage: BB + IBB + HBP + H / PA
# H - 2B - 3B - HR = 1B
# slugging: (total number of bases per AB on average) 1B + 22B + 33B + 4HR / AB

# On-base + slugging: Adding them together (OPS)
# Figure out undervalues players
# Figure out if a player is good in long-term... Should you spend a lot on a long contract or not.

df_bat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13755 entries, 0 to 13754
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           13755 non-null  int64
 1   playerID             13755 non-null  object
 2   yearID               13755 non-null  int64
 3   stint                13755 non-null  int64
 4   teamID               13755 non-null  object
 5   lgID                 13755 non-null  object
 6   G                    13755 non-null  int64
 7   AB                   13755 non-null  float64
 8   R                    13755 non-null  float64
 9   H                    13755 non-null  float64
 10  2B                   13755 non-null  float64
 11  3B                   13755 non-null  float64
 12  HR                   13755 non-null  float64
 13  RBI                  13755 non-null  float64
 14  SB                   13755 non-null  float64
 15  CS                   13755 non-null  float64
 16  BB                   13755 non-null  float64
 17  SO                   13755 non-null  float64
 18  IBB                  13755 non-null  float64
 19  HBP                  13755 non-null  float64
 20  SH                   13755 non-null  float64
 21  SF                   13755 non-null  float64
 22  GIDP                 13755 non-null  float64
 23  birthYear            13755 non-null  float64
 24  weight               13755 non-null  float64
 25  height               13755 non-null  float64
 26  debut                13755 non-null  object
 27  current_age          13755 non-null  float64
 28  years_of_experience  13755 non-null  int64
dtypes: float64(20), int64(5), object(4)
memory usage: 3.0+ MB